### ISSUE TITLE
init.sls jinja template could not be parsed.

### ISSUE THREAD

**Issue by Johnz86** [saltstack-formulas/openldap-formula#2]
Today I tried to use this formula with my vagrant ubuntu precise machine. The init.sls could not be parsed because of incorrectly closed conditional statements.

The resulting file that worked for me looks like this:

```
ldap:
  pkg:
    - installed
    {% if grains['os_family'] == 'RedHat' %}
    - pkgs:
      - openldap-servers
      - openldap-clients
    {% elif grains['os_family'] == 'Debian'%}
    - pkgs: 
      - slapd
      - ldap-utils
    {% else %}
    - name: openldap
    {% endif %}
  file:
    - managed
    {% if grains['os_family'] == 'Debian' %}
    - name: /etc/ldap/ldap.conf
    {% else %}
    - name: /etc/openldap/ldap.conf
    {% endif %}
    - source: salt://openldap/files/ldap.conf
    - template: jinja
    - user: root
    - ldap_uri: "ldaps://ldap01.domain.com/ ldaps://p-chi-ldap02.domain.com/"
    - ldap_base: "dc=domain,dc=com" 
    - group: root
    - mode: 644
    - makedirs: True
    - require:
      - pkg: ldap
```
